IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TIPOS_EVENTO' AND type = 'U')
BEGIN
  CREATE TABLE TIPOS_EVENTO (
    id_tipo INT          NOT NULL IDENTITY(1,1),
    nombre  NVARCHAR(80) NOT NULL,
    CONSTRAINT PK_TIPOS_EVENTO PRIMARY KEY (id_tipo)
  );
END
